// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-creators.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_creators_default = defineTool({
  name: "search_creators",
  title: "Search creators on Kretopia",
  description: "Search the Kretopia creative universe by name, role, skill, or location. Returns public Passport summaries.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Free-text search: name, role, skill, or city."),
    limit: z.number().int().min(1).max(25).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const cap = limit ?? 10;
    const q = `%${query}%`;
    const { data, error } = await sb.from("profiles").select("user_id, full_name, role, job_title, industry, location, bio, avatar_url, badge, level").or(
      `full_name.ilike.${q},role.ilike.${q},job_title.ilike.${q},industry.ilike.${q},location.ilike.${q}`
    ).limit(cap);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { creators: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-passport.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_passport_default = defineTool2({
  name: "get_my_passport",
  title: "Get my Creative Passport",
  description: "Returns the signed-in user's Kretopia Creative Passport: identity, role, skills, socials, and standing.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("profiles").select(
      "user_id, full_name, role, job_title, industry, location, bio, avatar_url, website, instagram_url, youtube_url, spotify_url, professional_skills, passion_skills, badge, level, xp, subscription_tier"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { passport: data }
    };
  }
});

// src/lib/mcp/tools/list-my-studios.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_studios_default = defineTool3({
  name: "list_my_studios",
  title: "List my Studios",
  description: "List the signed-in user's Studios (projects) \u2014 active creative workspaces they own or created.",
  inputSchema: {
    status: z2.enum(["active", "completed", "archived", "all"]).optional().describe("Filter by status (default 'active')."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("projects").select("id, title, description, status, workspace_type, mood, deadline, created_at, updated_at").eq("created_by", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status && status !== "all") q = q.eq("status", status);
    else if (!status) q = q.eq("status", "active");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { studios: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-scouted-gigs.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_scouted_gigs_default = defineTool4({
  name: "list_scouted_gigs",
  title: "List Scout opportunities",
  description: "Returns the signed-in user's most recent Scout opportunities (AI-scouted gigs across the web).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max gigs to return (default 15)."),
    min_fit_score: z3.number().min(0).max(100).optional().describe("Only return gigs with fit_score >= this value.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit, min_fit_score }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("scouted_gigs").select(
      "id, title, company, location, remote, compensation, deadline, apply_url, source, source_name, fit_score, fit_reason, description, scouted_at"
    ).eq("target_user_id", ctx.getUserId()).order("scouted_at", { ascending: false }).limit(limit ?? 15);
    if (typeof min_fit_score === "number") q = q.gte("fit_score", min_fit_score);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { gigs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-credits.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_credits_default = defineTool5({
  name: "list_my_credits",
  title: "List my Stamps (credits)",
  description: "Returns the signed-in user's verified Kretopia Stamps \u2014 IMDb-style credits for creative work.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max credits (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data, error } = await sb.from("credits").select(
      "id, project_name, role, year, platform, url, thumbnail_url, verification_status, credit_category, client_brand, description, is_featured, created_at"
    ).eq("user_id", ctx.getUserId()).order("year", { ascending: false, nullsFirst: false }).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { credits: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kwmcocsitwssrtzkdojh";
var mcp_default = defineMcp({
  name: "kretopia-mcp",
  title: "Kretopia \u2014 Creative OS",
  version: "0.1.0",
  instructions: "Kretopia is the operating system for creative careers. Use these tools to search the creative universe, read the signed-in user's Creative Passport and Stamps (credits), list their Studios (projects), and surface Scout opportunities. All tools act as the signed-in Kretopia user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_creators_default, get_my_passport_default, list_my_studios_default, list_scouted_gigs_default, list_my_credits_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
